const fs=require('fs');const assert=require('assert');const vm=require('vm');
const index=fs.readFileSync('index.html','utf8');const app=fs.readFileSync('app.js','utf8');
const tools=['機房 / 資料中心整合估算','換氣量計算','冷負載估算','水管管徑建議','壓差估算流量','kW 估算電流','溫度換算','流量換算','壓力換算','流速換算','電力單位換算','意見回饋'];
tools.forEach(t=>assert(index.includes(t)||app.includes(t),`missing tool ${t}`));
assert(!index.includes("<article class=\"card\"><h2>流量換算</h2></article>"),'empty shell exists');
assert(app.includes('toolRegistry')&&app.includes('openTool'));
['renderHome','panel','bindConverter','initTempTool','initFlowTool','initPressureTool','initVelocityTool','initPowerUnitTool','initKwiTool','initPipeSuggestTool','initDpFlowTool','initVentilationTool','initCoolingLoadTool','initDataCenterLoadTool','initDcSharedTool','renderMobileResultCards'].forEach(fn=>assert(app.includes(fn),`missing ${fn}`));
['kwi-p','kwi-v','kwi-ph','kwi-pf','dc-racks','dc-kw','dc-ups','dc-pue','vent-l','vent-w','vent-h','vent-ach','cool-l','cool-w','cool-mode'].forEach(k=>assert(app.includes(k),`missing field ${k}`));
assert(app.includes('v*9/5+32'));assert(app.includes('v*60'));assert(app.includes('v*1000'));assert(app.includes('v*3.6'));
const ctx={window:{}};vm.runInNewContext(fs.readFileSync('src/data/pipeSizes.js','utf8'),ctx);const pipe=ctx.window.PipeSizes;
assert(pipe.getRecommendedPipeForFlow(5000,3).pipe.a==='200A');
assert(app.includes('1FAIpQLSc95R0vPbKHLP9kP4MkCxsTVxk0aHTw4iCqlEHNb-Aa6RSWNQ'));
assert(!app.includes('flowAt25')&&!app.includes('flowAt3')&&!app.includes('rawFlowLpm = flow'));
console.log('smoke ok');
