name: iOS Build Only Manual
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: .
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: {channel: stable}
      - run: flutter pub get
      - run: flutter build ios --no-codesign
