name: iOS Build Only

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios-build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Clean project
        run: |
          flutter clean

      - name: Build iOS (NO CODESIGN)
        run: |
          flutter build ios --release --no-codesign

