name: iOS Release TestFlight

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --release

      - name: Upload to TestFlight
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
        run: |
          echo "$APPSTORE_PRIVATE_KEY" > AuthKey.p8

          xcrun altool --upload-app \
            -f build/ios/ipa/*.ipa \
            --type ios \
            --apiKey $APPSTORE_KEY_ID \
            --apiIssuer $APPSTORE_ISSUER_ID
